/**
 * Print-on-Demand Products Database
 */

import { getPathPrefixes } from './layout.js';

const img = (name) => `${getPathPrefixes().assets}images/${name}`;

export const products = [
  {
    id: 'prod-01',
    name: 'Heavyweight Premium Cotton T-Shirt',
    category: 'apparel',
    categoryLabel: 'Custom Apparel',
    basePrice: 19.99,
    bulkPrice: 12.50,
    tag: 'Best Seller',
    rating: 4.9,
    reviewsCount: 428,
    colors: ['#FFFFFF', '#111111', '#FFB800', '#2563EB', '#4B5563'],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    image: img('tee-white.jpg'),
    description: '100% Ring-spun combed organic cotton (240 GSM). High-definition Direct-to-Garment (DTG) print with ultra-sharp details and zero wash fade.',
    printLocations: ['Front Chest', 'Back Full', 'Left Sleeve']
  },
  {
    id: 'prod-02',
    name: 'Oversized Streetwear Fleece Hoodie',
    category: 'apparel',
    categoryLabel: 'Custom Apparel',
    basePrice: 42.00,
    bulkPrice: 28.00,
    tag: 'Trending',
    rating: 5.0,
    reviewsCount: 312,
    colors: ['#FFFFFF', '#111111', '#E5E7EB', '#D97706'],
    sizes: ['M', 'L', 'XL', '2XL'],
    image: img('hoodie-retro.jpg'),
    description: 'Ultra-soft 380 GSM brushed fleece with double-lined hood, kangaroo pouch, and reinforced ribbed cuffs. Perfect for branded drops.',
    printLocations: ['Front Center', 'Back Poster', 'Hood Edge']
  },
  {
    id: 'prod-03',
    name: 'Matte Ceramic Coffee Mug (15oz)',
    category: 'drinkware',
    categoryLabel: 'Drinkware & Mugs',
    basePrice: 14.50,
    bulkPrice: 7.90,
    tag: 'Top Gift',
    rating: 4.8,
    reviewsCount: 195,
    colors: ['#FFFFFF', '#111111', '#FFB800'],
    sizes: ['11oz', '15oz'],
    image: img('mug-ceramic.jpg'),
    description: 'Premium ceramic with ergonomic C-handle. 360-degree all-around dye-sublimation print, microwave & dishwasher safe.',
    printLocations: ['Full Wrap 360°', 'Front Logo', 'Double Sided']
  },
  {
    id: 'prod-04',
    name: 'Heavy Duty Organic Canvas Tote Bag',
    category: 'accessories',
    categoryLabel: 'Bags & Accessories',
    basePrice: 16.00,
    bulkPrice: 8.50,
    tag: 'Eco Friendly',
    rating: 4.9,
    reviewsCount: 260,
    colors: ['#F3F4F6', '#111111', '#FEF3C7'],
    sizes: ['Standard (15x16 in)', 'Large Gusset'],
    image: img('tote-canvas.jpg'),
    description: '12oz durable organic canvas with reinforced cross-stitched handles. Crisp vector screen-printing with eco-friendly water-based inks.',
    printLocations: ['Front Center', 'Double Sided']
  },
  {
    id: 'prod-05',
    name: 'Impact Armor MagSafe Phone Case',
    category: 'accessories',
    categoryLabel: 'Phone Case & Tech',
    basePrice: 22.00,
    bulkPrice: 13.00,
    tag: 'High Margin',
    rating: 4.9,
    reviewsCount: 540,
    colors: ['#111111', '#FFFFFF', '#FFB800'],
    sizes: ['iPhone 16 Pro', 'iPhone 15', 'Galaxy S24 Ultra', 'Pixel 9 Pro'],
    image: img('phone-case.jpg'),
    description: 'Dual-layer shockproof polycarbonate with raised camera ring. Glossy UV scratch-resistant wrap-around artwork finish.',
    printLocations: ['Back Full Bleed', 'Matte Edge']
  },
  {
    id: 'prod-06',
    name: 'Vintage Washed Cotton Bucket Hat',
    category: 'apparel',
    categoryLabel: 'Headwear',
    basePrice: 24.00,
    bulkPrice: 14.20,
    tag: 'New Drop',
    rating: 4.7,
    reviewsCount: 88,
    colors: ['#D1D5DB', '#111111', '#FEF08A'],
    sizes: ['One Size Fits All'],
    image: img('bucket-hat.jpg'),
    description: '100% enzyme-washed cotton twill with brass eyelets for breathability. 3D high-density embroidered patch or flat print.',
    printLocations: ['Front Center 3D Embroidery']
  },
  {
    id: 'prod-07',
    name: 'Vacuum Insulated Stainless Tumbler (20oz)',
    category: 'drinkware',
    categoryLabel: 'Drinkware & Mugs',
    basePrice: 28.00,
    bulkPrice: 16.50,
    tag: 'Popular',
    rating: 4.9,
    reviewsCount: 168,
    colors: ['#FFFFFF', '#111111', '#E5E7EB'],
    sizes: ['20oz', '30oz'],
    image: img('tumbler-steel.jpg'),
    description: 'Double-wall vacuum insulation keeps drinks ice cold for 24h or piping hot for 12h. Precision laser engraving & UV color prints.',
    printLocations: ['Laser Etch Front', 'Color UV Print']
  },
  {
    id: 'prod-08',
    name: 'Die-Cut Holographic & Vinyl Sticker Pack',
    category: 'accessories',
    categoryLabel: 'Bags & Accessories',
    basePrice: 9.99,
    bulkPrice: 2.80,
    tag: 'Quick Turnaround',
    rating: 5.0,
    reviewsCount: 710,
    colors: ['#FFB800', '#FFFFFF'],
    sizes: ['50 Pack', '100 Pack', '500 Bulk'],
    image: img('sticker-pack.jpg'),
    description: 'Weatherproof vinyl stickers with UV lamination. Thick, durable, scratch-resistant and dishwasher proof.',
    printLocations: ['Custom Cut Shape']
  },
  {
    id: 'prod-09',
    name: 'Oversize Drop-Shoulder Hoodie',
    category: 'apparel',
    categoryLabel: 'Custom Apparel',
    basePrice: 46.00,
    bulkPrice: 30.00,
    tag: 'Bestseller',
    rating: 4.9,
    reviewsCount: 204,
    colors: ['#FFFFFF', '#111111', '#A78BFA', '#F472B6'],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    image: img('hoodie-oversize.jpg'),
    description: 'Boxy drop-shoulder cut with oversized sleeves and a heavyweight 400 GSM French terry fleece. Premium streetwear canvas.',
    printLocations: ['Chest Left', 'Back Print', 'Filled Inner Shell']
  },
  {
    id: 'prod-10',
    name: '6-Panel Structured Snapback Cap',
    category: 'apparel',
    categoryLabel: 'Headwear',
    basePrice: 26.00,
    bulkPrice: 15.00,
    tag: 'Style Icon',
    rating: 4.8,
    reviewsCount: 156,
    colors: ['#111111', '#FFFFFF', '#DC2626', '#2563EB'],
    sizes: ['Adjustable OSFA'],
    image: img('cap-snapback.jpg'),
    description: 'High-profile structured crown with a flat visor and premium raised 3D embroidery. Snap-and-go back closure.',
    printLocations: ['Front 3D Puff', 'Side Panels', 'Back Logo']
  },
  {
    id: 'prod-11',
    name: 'Hardcover Custom Notebook & Journal',
    category: 'accessories',
    categoryLabel: 'Office & Desk',
    basePrice: 18.00,
    bulkPrice: 9.80,
    tag: 'Corporate Fav',
    rating: 4.9,
    reviewsCount: 190,
    colors: ['#111111', '#FFFFFF', '#FFB800'],
    sizes: ['A5', 'A4', 'B5'],
    image: img('notebook.jpg'),
    description: 'Lay-flat hardcover journal with 180 GSM bleed-proof paper. Full-wrap soft-touch matte print cover.',
    printLocations: ['Front Cover', 'Full Wrap', 'Spine']
  },
  {
    id: 'prod-12',
    name: 'Zip-Top Canvas Utility Pouch',
    category: 'accessories',
    categoryLabel: 'Bags & Accessories',
    basePrice: 15.00,
    bulkPrice: 8.20,
    tag: 'Everyday Carry',
    rating: 4.7,
    reviewsCount: 92,
    colors: ['#111111', '#F3F4F6', '#059669'],
    sizes: ['Mini (7x5 in)', 'Standard (9x6 in)'],
    image: img('pouch.jpg'),
    description: 'Heavyweight canvas zip pouch for cosmetics, cables, or dice. Durable wrap print with water-repellent finish.',
    printLocations: ['Front', 'Full Wrap']
  },
  {
    id: 'prod-13',
    name: 'Linen Print Cushion Cover',
    category: 'lifestyle',
    categoryLabel: 'Home & Lifestyle',
    basePrice: 20.00,
    bulkPrice: 11.50,
    tag: 'Home Range',
    rating: 4.8,
    reviewsCount: 74,
    colors: ['#F3F4F6', '#111111', '#FDE68A'],
    sizes: ['45 x 45 cm', '50 x 50 cm'],
    image: img('cushion.jpg'),
    description: 'Soft-touch linen blend cushion with hidden zip. Vibrant dye-sublimation front print, machine washable.',
    printLocations: ['Front Panel', 'Double Sided']
  },
  {
    id: 'prod-14',
    name: 'All-Over Print Desk Mat',
    category: 'lifestyle',
    categoryLabel: 'Office & Desk',
    basePrice: 24.00,
    bulkPrice: 14.00,
    tag: 'Workspace Pro',
    rating: 4.9,
    reviewsCount: 130,
    colors: ['#111111', '#FFB800', '#FFFFFF'],
    sizes: ['800 x 300 mm', '900 x 400 mm'],
    image: img('abstract-3d.jpg'),
    description: 'Anti-slip neoprene desk mat with stitched edges and a smooth polyester surface for fast mouse tracking.',
    printLocations: ['Full Surface Print']
  },
  {
    id: 'prod-15',
    name: 'Bulk Corporate T-Shirt Pack (10-Pack)',
    category: 'apparel',
    categoryLabel: 'Custom Apparel',
    basePrice: 149.99,
    bulkPrice: 99.00,
    tag: 'Wholesale',
    rating: 4.8,
    reviewsCount: 61,
    colors: ['#FFFFFF', '#111111', '#2563EB', '#FFB800'],
    sizes: ['S-XL Mix', 'S-2XL Mix', 'M-XL Mix'],
    image: img('tee-rack.jpg'),
    description: 'Ten heavyweight 240 GSM tees shipped in one sticker-friendly pack. Ideal for corporate kits, events, and creator launch bundles.',
    printLocations: ['Front Logo', 'Back Logo', 'Sleeve Mark']
  },
  {
    id: 'prod-16',
    name: 'Premium Phone Mockup Render Pack',
    category: 'lifestyle',
    categoryLabel: 'Digital & Print Assets',
    basePrice: 12.99,
    bulkPrice: 5.99,
    tag: 'Digital',
    rating: 5.0,
    reviewsCount: 215,
    colors: ['#FFB800', '#FFFFFF'],
    sizes: ['Single Mockup', 'Bundle of 5', 'Bundle of 12'],
    image: img('phone-mockup.jpg'),
    description: 'High-resolution 300 DPI phone mockup renders in light and dark scenes. Perfect for showcasing your custom prints on social media.',
    printLocations: ['Digital Download']
  }
];

export const sampleArtworks = [
  {
    id: 'art-1',
    name: 'Retro Sunrise Wave',
    svg: `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><circle cx="50" cy="50" r="44" fill="#FFB800"/><path d="M15 65C30 55 40 75 55 60C70 45 80 65 85 55V85H15V65Z" fill="#111111"/><circle cx="50" cy="35" r="14" fill="#FFFFFF"/><path d="M22 80H78" stroke="#FFFFFF" stroke-width="3" stroke-linecap="round"/></svg>`
  },
  {
    id: 'art-2',
    name: 'Urban Cyber Skull',
    svg: `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="10" y="10" width="80" height="80" rx="16" fill="#111111"/><circle cx="36" cy="42" r="8" fill="#FFB800"/><circle cx="64" cy="42" r="8" fill="#FFB800"/><path d="M35 68H65" stroke="#FFB800" stroke-width="5" stroke-linecap="round"/><path d="M42 60V76M50 60V76M58 60V76" stroke="#111111" stroke-width="3"/></svg>`
  },
  {
    id: 'art-3',
    name: 'Tokyo Street Typo',
    svg: `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="100" height="100" rx="12" fill="#18181B"/><text x="50" y="44" font-family="sans-serif" font-weight="900" font-size="20" fill="#FFB800" text-anchor="middle">CREATIVE</text><text x="50" y="68" font-family="sans-serif" font-weight="800" font-size="14" fill="#FFFFFF" text-anchor="middle">STUDIO 26</text></svg>`
  },
  {
    id: 'art-4',
    name: 'Minimalist Monogram',
    svg: `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><circle cx="50" cy="50" r="42" stroke="#FFB800" stroke-width="4"/><text x="50" y="62" font-family="serif" font-weight="900" font-size="36" fill="#111111" text-anchor="middle">3A</text></svg>`
  }
];